// Code generated by protoc-gen-go. DO NOT EDIT.
// source: request.proto

package request

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 定义请求结构体
type Request struct {
	Query                []byte   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	WxOpenId             []byte   `protobuf:"bytes,2,opt,name=wxOpenId,proto3" json:"wxOpenId,omitempty"`
	Code                 int32    `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f73548e33e655fe, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetQuery() []byte {
	if m != nil {
		return m.Query
	}
	return nil
}

func (m *Request) GetWxOpenId() []byte {
	if m != nil {
		return m.WxOpenId
	}
	return nil
}

func (m *Request) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func init() {
	proto.RegisterType((*Request)(nil), "request.Request")
}

func init() { proto.RegisterFile("request.proto", fileDescriptor_7f73548e33e655fe) }

var fileDescriptor_7f73548e33e655fe = []byte{
	// 107 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2d, 0x4a, 0x2d, 0x2c,
	0x4d, 0x2d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0xfc, 0xb9,
	0xd8, 0x83, 0x20, 0x4c, 0x21, 0x11, 0x2e, 0xd6, 0xc2, 0xd2, 0xd4, 0xa2, 0x4a, 0x09, 0x46, 0x05,
	0x46, 0x0d, 0x9e, 0x20, 0x08, 0x47, 0x48, 0x8a, 0x8b, 0xa3, 0xbc, 0xc2, 0xbf, 0x20, 0x35, 0xcf,
	0x33, 0x45, 0x82, 0x09, 0x2c, 0x01, 0xe7, 0x0b, 0x09, 0x71, 0xb1, 0x24, 0xe7, 0xa7, 0xa4, 0x4a,
	0x30, 0x2b, 0x30, 0x6a, 0xb0, 0x06, 0x81, 0xd9, 0x49, 0x6c, 0x60, 0x0b, 0x8c, 0x01, 0x01, 0x00,
	0x00, 0xff, 0xff, 0xbb, 0x57, 0xed, 0x82, 0x71, 0x00, 0x00, 0x00,
}
