// Code generated by protoc-gen-go. DO NOT EDIT.
// source: message.proto

package message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 定义一个 "类" AMiniRequest :: 这个会名称之后会用到的
type AMiniRequest struct {
	Query                string   `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AMiniRequest) Reset()         { *m = AMiniRequest{} }
func (m *AMiniRequest) String() string { return proto.CompactTextString(m) }
func (*AMiniRequest) ProtoMessage()    {}
func (*AMiniRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{0}
}

func (m *AMiniRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AMiniRequest.Unmarshal(m, b)
}
func (m *AMiniRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AMiniRequest.Marshal(b, m, deterministic)
}
func (m *AMiniRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AMiniRequest.Merge(m, src)
}
func (m *AMiniRequest) XXX_Size() int {
	return xxx_messageInfo_AMiniRequest.Size(m)
}
func (m *AMiniRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AMiniRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AMiniRequest proto.InternalMessageInfo

func (m *AMiniRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

type AMiniResponse struct {
	OpenId               string   `protobuf:"bytes,1,opt,name=open_id,json=openId,proto3" json:"open_id,omitempty"`
	Jwt                  string   `protobuf:"bytes,2,opt,name=jwt,proto3" json:"jwt,omitempty"`
	Address              string   `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Age                  int64    `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AMiniResponse) Reset()         { *m = AMiniResponse{} }
func (m *AMiniResponse) String() string { return proto.CompactTextString(m) }
func (*AMiniResponse) ProtoMessage()    {}
func (*AMiniResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{1}
}

func (m *AMiniResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AMiniResponse.Unmarshal(m, b)
}
func (m *AMiniResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AMiniResponse.Marshal(b, m, deterministic)
}
func (m *AMiniResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AMiniResponse.Merge(m, src)
}
func (m *AMiniResponse) XXX_Size() int {
	return xxx_messageInfo_AMiniResponse.Size(m)
}
func (m *AMiniResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AMiniResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AMiniResponse proto.InternalMessageInfo

func (m *AMiniResponse) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *AMiniResponse) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

func (m *AMiniResponse) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *AMiniResponse) GetAge() int64 {
	if m != nil {
		return m.Age
	}
	return 0
}

// post 请求用的
type AMiniPostRequest struct {
	Jwt                  string   `protobuf:"bytes,1,opt,name=jwt,proto3" json:"jwt,omitempty"`
	Category             string   `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AMiniPostRequest) Reset()         { *m = AMiniPostRequest{} }
func (m *AMiniPostRequest) String() string { return proto.CompactTextString(m) }
func (*AMiniPostRequest) ProtoMessage()    {}
func (*AMiniPostRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{2}
}

func (m *AMiniPostRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AMiniPostRequest.Unmarshal(m, b)
}
func (m *AMiniPostRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AMiniPostRequest.Marshal(b, m, deterministic)
}
func (m *AMiniPostRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AMiniPostRequest.Merge(m, src)
}
func (m *AMiniPostRequest) XXX_Size() int {
	return xxx_messageInfo_AMiniPostRequest.Size(m)
}
func (m *AMiniPostRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AMiniPostRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AMiniPostRequest proto.InternalMessageInfo

func (m *AMiniPostRequest) GetJwt() string {
	if m != nil {
		return m.Jwt
	}
	return ""
}

func (m *AMiniPostRequest) GetCategory() string {
	if m != nil {
		return m.Category
	}
	return ""
}

type AMiniPostResponse struct {
	ErrCode              int32    `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMessage           string   `protobuf:"bytes,2,opt,name=err_message,json=errMessage,proto3" json:"err_message,omitempty"`
	Category             []string `protobuf:"bytes,3,rep,name=category,proto3" json:"category,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AMiniPostResponse) Reset()         { *m = AMiniPostResponse{} }
func (m *AMiniPostResponse) String() string { return proto.CompactTextString(m) }
func (*AMiniPostResponse) ProtoMessage()    {}
func (*AMiniPostResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_33c57e4bae7b9afd, []int{3}
}

func (m *AMiniPostResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AMiniPostResponse.Unmarshal(m, b)
}
func (m *AMiniPostResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AMiniPostResponse.Marshal(b, m, deterministic)
}
func (m *AMiniPostResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AMiniPostResponse.Merge(m, src)
}
func (m *AMiniPostResponse) XXX_Size() int {
	return xxx_messageInfo_AMiniPostResponse.Size(m)
}
func (m *AMiniPostResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AMiniPostResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AMiniPostResponse proto.InternalMessageInfo

func (m *AMiniPostResponse) GetErrCode() int32 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *AMiniPostResponse) GetErrMessage() string {
	if m != nil {
		return m.ErrMessage
	}
	return ""
}

func (m *AMiniPostResponse) GetCategory() []string {
	if m != nil {
		return m.Category
	}
	return nil
}

func init() {
	proto.RegisterType((*AMiniRequest)(nil), "AMiniRequest")
	proto.RegisterType((*AMiniResponse)(nil), "AMiniResponse")
	proto.RegisterType((*AMiniPostRequest)(nil), "AMiniPostRequest")
	proto.RegisterType((*AMiniPostResponse)(nil), "AMiniPostResponse")
}

func init() {
	proto.RegisterFile("message.proto", fileDescriptor_33c57e4bae7b9afd)
}

var fileDescriptor_33c57e4bae7b9afd = []byte{
	// 232 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0x59, 0x63, 0xbb, 0x75, 0xb4, 0x50, 0x83, 0x60, 0xf4, 0xe2, 0x12, 0x3c, 0xf4, 0xe4,
	0xc5, 0x3f, 0xa0, 0x78, 0xf2, 0x50, 0x90, 0xfc, 0x81, 0x12, 0x9b, 0x71, 0x59, 0xc5, 0x9d, 0xed,
	0x4c, 0x8a, 0xf4, 0xdf, 0x4b, 0xd2, 0x54, 0xdb, 0xdb, 0xbc, 0x37, 0x8f, 0xef, 0x0d, 0x03, 0xd3,
	0x6f, 0x14, 0xf1, 0x2d, 0x3e, 0x0c, 0x4c, 0x91, 0xec, 0x3d, 0x5c, 0x3c, 0x2f, 0xba, 0xbe, 0x73,
	0xb8, 0xde, 0xa0, 0x44, 0x7d, 0x05, 0xa3, 0xf5, 0x06, 0x79, 0x6b, 0xaa, 0xa6, 0x9a, 0x9f, 0xb9,
	0x9d, 0xb0, 0x1f, 0x30, 0x2d, 0x29, 0x19, 0xa8, 0x17, 0xd4, 0xd7, 0x50, 0xd3, 0x80, 0xfd, 0xb2,
	0x0b, 0x25, 0x38, 0x4e, 0xf2, 0x35, 0xe8, 0x19, 0xa8, 0xcf, 0x9f, 0x68, 0x4e, 0xb2, 0x99, 0x46,
	0x6d, 0xa0, 0xf6, 0x21, 0x30, 0x8a, 0x18, 0x95, 0xdd, 0xbd, 0x4c, 0x59, 0xdf, 0xa2, 0x39, 0x6d,
	0xaa, 0xb9, 0x72, 0x69, 0xb4, 0x4f, 0x30, 0xcb, 0x3d, 0x6f, 0x24, 0x71, 0x7f, 0x51, 0x21, 0x56,
	0xff, 0xc4, 0x5b, 0x98, 0xac, 0x7c, 0xc4, 0x96, 0x78, 0x5b, 0x8a, 0xfe, 0xb4, 0xfd, 0x82, 0xcb,
	0x03, 0x42, 0xb9, 0xf6, 0x06, 0x26, 0xc8, 0xbc, 0x5c, 0x51, 0xc0, 0xcc, 0x19, 0xb9, 0x1a, 0x99,
	0x5f, 0x28, 0xa0, 0xbe, 0x83, 0xf3, 0xb4, 0x2a, 0x4f, 0x29, 0x38, 0x40, 0xe6, 0xc5, 0xce, 0x39,
	0x2a, 0x53, 0x8d, 0x3a, 0x2c, 0x7b, 0x1f, 0xe7, 0x1f, 0x3e, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff,
	0x94, 0xda, 0x22, 0x43, 0x54, 0x01, 0x00, 0x00,
}
