// Code generated by protoc-gen-go. DO NOT EDIT.
// source: err_info.proto

package err

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ErrInfo 这个名称在JS 提取描述的时候会用到
type ErrInfo struct {
	AppId                string   `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	PageUrl              string   `protobuf:"bytes,2,opt,name=page_url,json=pageUrl,proto3" json:"page_url,omitempty"`
	ErrInfo              string   `protobuf:"bytes,3,opt,name=err_info,json=errInfo,proto3" json:"err_info,omitempty"`
	ErrTime              int64    `protobuf:"varint,4,opt,name=err_time,json=errTime,proto3" json:"err_time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrInfo) Reset()         { *m = ErrInfo{} }
func (m *ErrInfo) String() string { return proto.CompactTextString(m) }
func (*ErrInfo) ProtoMessage()    {}
func (*ErrInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_48d13aba0c3e0e9b, []int{0}
}

func (m *ErrInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrInfo.Unmarshal(m, b)
}
func (m *ErrInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrInfo.Marshal(b, m, deterministic)
}
func (m *ErrInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrInfo.Merge(m, src)
}
func (m *ErrInfo) XXX_Size() int {
	return xxx_messageInfo_ErrInfo.Size(m)
}
func (m *ErrInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ErrInfo proto.InternalMessageInfo

func (m *ErrInfo) GetAppId() string {
	if m != nil {
		return m.AppId
	}
	return ""
}

func (m *ErrInfo) GetPageUrl() string {
	if m != nil {
		return m.PageUrl
	}
	return ""
}

func (m *ErrInfo) GetErrInfo() string {
	if m != nil {
		return m.ErrInfo
	}
	return ""
}

func (m *ErrInfo) GetErrTime() int64 {
	if m != nil {
		return m.ErrTime
	}
	return 0
}

func init() {
	proto.RegisterType((*ErrInfo)(nil), "err.ErrInfo")
}

func init() { proto.RegisterFile("err_info.proto", fileDescriptor_48d13aba0c3e0e9b) }

var fileDescriptor_48d13aba0c3e0e9b = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4b, 0x2d, 0x2a, 0x8a,
	0xcf, 0xcc, 0x4b, 0xcb, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x2d, 0x2a, 0x52,
	0x2a, 0xe4, 0x62, 0x77, 0x2d, 0x2a, 0xf2, 0xcc, 0x4b, 0xcb, 0x17, 0x12, 0xe5, 0x62, 0x4b, 0x2c,
	0x28, 0x88, 0xcf, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x62, 0x4d, 0x2c, 0x28, 0xf0,
	0x4c, 0x11, 0x92, 0xe4, 0xe2, 0x28, 0x48, 0x4c, 0x4f, 0x8d, 0x2f, 0x2d, 0xca, 0x91, 0x60, 0x02,
	0x4b, 0xb0, 0x83, 0xf8, 0xa1, 0x45, 0x39, 0x20, 0x29, 0x98, 0x99, 0x12, 0xcc, 0x10, 0xa9, 0x54,
	0xa8, 0x61, 0x50, 0xa9, 0x92, 0xcc, 0xdc, 0x54, 0x09, 0x16, 0x05, 0x46, 0x0d, 0x66, 0xb0, 0x54,
	0x48, 0x66, 0x6e, 0x6a, 0x12, 0x1b, 0xd8, 0x7a, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1d,
	0x98, 0xd8, 0xab, 0x90, 0x00, 0x00, 0x00,
}
