// Code generated by protoc-gen-go. DO NOT EDIT.
// source: err_report.proto

package err

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 请求结构体, 这里嵌套进入了一个 err.ErrInfo
type ErrReportRequest struct {
	ErrInfo              *ErrInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo,proto3" json:"err_info,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ErrReportRequest) Reset()         { *m = ErrReportRequest{} }
func (m *ErrReportRequest) String() string { return proto.CompactTextString(m) }
func (*ErrReportRequest) ProtoMessage()    {}
func (*ErrReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6924d237e347893b, []int{0}
}

func (m *ErrReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrReportRequest.Unmarshal(m, b)
}
func (m *ErrReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrReportRequest.Marshal(b, m, deterministic)
}
func (m *ErrReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrReportRequest.Merge(m, src)
}
func (m *ErrReportRequest) XXX_Size() int {
	return xxx_messageInfo_ErrReportRequest.Size(m)
}
func (m *ErrReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ErrReportRequest proto.InternalMessageInfo

func (m *ErrReportRequest) GetErrInfo() *ErrInfo {
	if m != nil {
		return m.ErrInfo
	}
	return nil
}

func (m *ErrReportRequest) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

//
type ErrReportResponse struct {
	ErrCode              int64       `protobuf:"varint,1,opt,name=err_code,json=errCode,proto3" json:"err_code,omitempty"`
	ErrMessage           string      `protobuf:"bytes,2,opt,name=err_message,json=errMessage,proto3" json:"err_message,omitempty"`
	ServerInfo           *ServerInfo `protobuf:"bytes,3,opt,name=server_info,json=serverInfo,proto3" json:"server_info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ErrReportResponse) Reset()         { *m = ErrReportResponse{} }
func (m *ErrReportResponse) String() string { return proto.CompactTextString(m) }
func (*ErrReportResponse) ProtoMessage()    {}
func (*ErrReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6924d237e347893b, []int{1}
}

func (m *ErrReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ErrReportResponse.Unmarshal(m, b)
}
func (m *ErrReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ErrReportResponse.Marshal(b, m, deterministic)
}
func (m *ErrReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ErrReportResponse.Merge(m, src)
}
func (m *ErrReportResponse) XXX_Size() int {
	return xxx_messageInfo_ErrReportResponse.Size(m)
}
func (m *ErrReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ErrReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ErrReportResponse proto.InternalMessageInfo

func (m *ErrReportResponse) GetErrCode() int64 {
	if m != nil {
		return m.ErrCode
	}
	return 0
}

func (m *ErrReportResponse) GetErrMessage() string {
	if m != nil {
		return m.ErrMessage
	}
	return ""
}

func (m *ErrReportResponse) GetServerInfo() *ServerInfo {
	if m != nil {
		return m.ServerInfo
	}
	return nil
}

type ServerInfo struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerInfo) Reset()         { *m = ServerInfo{} }
func (m *ServerInfo) String() string { return proto.CompactTextString(m) }
func (*ServerInfo) ProtoMessage()    {}
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_6924d237e347893b, []int{2}
}

func (m *ServerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerInfo.Unmarshal(m, b)
}
func (m *ServerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerInfo.Marshal(b, m, deterministic)
}
func (m *ServerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerInfo.Merge(m, src)
}
func (m *ServerInfo) XXX_Size() int {
	return xxx_messageInfo_ServerInfo.Size(m)
}
func (m *ServerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServerInfo proto.InternalMessageInfo

func (m *ServerInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*ErrReportRequest)(nil), "err.ErrReportRequest")
	proto.RegisterType((*ErrReportResponse)(nil), "err.ErrReportResponse")
	proto.RegisterType((*ServerInfo)(nil), "err.ServerInfo")
}

func init() { proto.RegisterFile("err_report.proto", fileDescriptor_6924d237e347893b) }

var fileDescriptor_6924d237e347893b = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xb1, 0x4e, 0xc3, 0x40,
	0x10, 0x44, 0x65, 0x2c, 0x11, 0xb2, 0x8e, 0x20, 0x5c, 0x65, 0x68, 0x08, 0x2e, 0x20, 0x95, 0x85,
	0xe0, 0x13, 0x50, 0x0a, 0x0a, 0x9a, 0x83, 0x9a, 0x28, 0x38, 0x13, 0x14, 0x21, 0x6e, 0xcd, 0xac,
	0x49, 0xcf, 0x9f, 0x23, 0xdf, 0xc5, 0x40, 0xb7, 0xf7, 0x76, 0x35, 0xf3, 0x74, 0x32, 0x05, 0xb9,
	0x24, 0x5a, 0x65, 0x57, 0xb7, 0xd4, 0x4e, 0x5d, 0x0e, 0xf2, 0xfc, 0xb8, 0xc7, 0xdb, 0xb0, 0xd1,
	0x04, 0xab, 0x17, 0x99, 0x2e, 0x48, 0x1f, 0xef, 0x3c, 0x3e, 0xbf, 0x60, 0x9d, 0xbb, 0x96, 0xa3,
	0xe1, 0xaa, 0xcc, 0x66, 0xd9, 0xbc, 0xb8, 0x9d, 0xd4, 0x20, 0xeb, 0x05, 0xf9, 0x10, 0x36, 0xea,
	0x47, 0x48, 0x83, 0xbb, 0x94, 0xc9, 0xaa, 0x69, 0x60, 0xb6, 0xec, 0xf4, 0x1d, 0xa1, 0x3c, 0x98,
	0x65, 0xf3, 0xb1, 0x2f, 0x12, 0x7b, 0xee, 0x51, 0xf5, 0x9d, 0xc9, 0xe9, 0xbf, 0x02, 0x6b, 0x35,
	0x18, 0xdc, 0x59, 0x6a, 0x68, 0x74, 0x8d, 0xd8, 0x90, 0xc7, 0xcc, 0x7b, 0x5d, 0xc3, 0x5d, 0x48,
	0xd1, 0xaf, 0x3e, 0x60, 0xb6, 0x7a, 0xc3, 0x3e, 0x52, 0x40, 0x3e, 0x26, 0xe2, 0x6e, 0xa4, 0x30,
	0x70, 0x87, 0xbd, 0x60, 0x1e, 0x05, 0x4f, 0xa2, 0xe0, 0x53, 0xe4, 0xd1, 0x51, 0xec, 0x77, 0xae,
	0xae, 0x44, 0xfe, 0x36, 0xae, 0x94, 0xd1, 0x0e, 0xb4, 0xad, 0x86, 0x58, 0x3d, 0xf6, 0xc3, 0xf3,
	0xf5, 0x30, 0x7e, 0xc9, 0xdd, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x58, 0x8c, 0xe9, 0xba, 0x3b,
	0x01, 0x00, 0x00,
}
