// Code generated by protoc-gen-go. DO NOT EDIT.
// source: my.proto

package request

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type My struct {
	Age                  int32    `protobuf:"varint,1,opt,name=age,proto3" json:"age,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *My) Reset()         { *m = My{} }
func (m *My) String() string { return proto.CompactTextString(m) }
func (*My) ProtoMessage()    {}
func (*My) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a5798dc1fd57a96, []int{0}
}

func (m *My) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_My.Unmarshal(m, b)
}
func (m *My) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_My.Marshal(b, m, deterministic)
}
func (m *My) XXX_Merge(src proto.Message) {
	xxx_messageInfo_My.Merge(m, src)
}
func (m *My) XXX_Size() int {
	return xxx_messageInfo_My.Size(m)
}
func (m *My) XXX_DiscardUnknown() {
	xxx_messageInfo_My.DiscardUnknown(m)
}

var xxx_messageInfo_My proto.InternalMessageInfo

func (m *My) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *My) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*My)(nil), "request.my")
}

func init() { proto.RegisterFile("my.proto", fileDescriptor_2a5798dc1fd57a96) }

var fileDescriptor_2a5798dc1fd57a96 = []byte{
	// 87 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc8, 0xad, 0xd4, 0x2b,
	0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x51, 0xd2, 0xe2,
	0x62, 0xca, 0xad, 0x14, 0x12, 0xe0, 0x62, 0x4e, 0x4c, 0x4f, 0x95, 0x60, 0x54, 0x60, 0xd4, 0x60,
	0x0d, 0x02, 0x31, 0x85, 0x84, 0xb8, 0x58, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35,
	0x38, 0x83, 0xc0, 0xec, 0x24, 0x36, 0xb0, 0x5e, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1e,
	0xf8, 0x2d, 0x21, 0x47, 0x00, 0x00, 0x00,
}
