// Code generated by protoc-gen-go. DO NOT EDIT.
// source: index/index.proto

package index

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
	request "request"
	response "response"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("index/index.proto", fileDescriptor_91013751fa82c1bb) }

var fileDescriptor_91013751fa82c1bb = []byte{
	// 104 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcc, 0xcc, 0x4b, 0x49,
	0xad, 0xd0, 0x07, 0x93, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xac, 0x60, 0x8e, 0x94, 0x68,
	0x51, 0x6a, 0x61, 0x69, 0x6a, 0x71, 0x89, 0x3e, 0x94, 0x86, 0xc8, 0x4a, 0x89, 0x17, 0xa5, 0x16,
	0x17, 0xe4, 0xe7, 0x15, 0xa7, 0xea, 0xc3, 0x18, 0x10, 0x09, 0x23, 0x0b, 0x2e, 0x56, 0x4f, 0x90,
	0x46, 0x21, 0x7d, 0x18, 0x43, 0x40, 0x0f, 0xa6, 0x35, 0x08, 0x42, 0x4b, 0x09, 0xe9, 0xc1, 0x35,
	0x05, 0x41, 0x19, 0x4a, 0x0c, 0x49, 0x6c, 0x60, 0x03, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xe8, 0x7b, 0x9e, 0x2a, 0x8c, 0x00, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// IndexClient is the client API for Index service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type IndexClient interface {
	// 定义一个请求 index 的接口, 输入参数是 request.Request
	// 输出的参数是 response.Response
	Index(ctx context.Context, in *request.Request, opts ...grpc.CallOption) (*response.Response, error)
}

type indexClient struct {
	cc *grpc.ClientConn
}

func NewIndexClient(cc *grpc.ClientConn) IndexClient {
	return &indexClient{cc}
}

func (c *indexClient) Index(ctx context.Context, in *request.Request, opts ...grpc.CallOption) (*response.Response, error) {
	out := new(response.Response)
	err := c.cc.Invoke(ctx, "/index.Index/Index", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndexServer is the server API for Index service.
type IndexServer interface {
	// 定义一个请求 index 的接口, 输入参数是 request.Request
	// 输出的参数是 response.Response
	Index(context.Context, *request.Request) (*response.Response, error)
}

// UnimplementedIndexServer can be embedded to have forward compatible implementations.
type UnimplementedIndexServer struct {
}

func (*UnimplementedIndexServer) Index(ctx context.Context, req *request.Request) (*response.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Index not implemented")
}

func RegisterIndexServer(s *grpc.Server, srv IndexServer) {
	s.RegisterService(&_Index_serviceDesc, srv)
}

func _Index_Index_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexServer).Index(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/index.Index/Index",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexServer).Index(ctx, req.(*request.Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _Index_serviceDesc = grpc.ServiceDesc{
	ServiceName: "index.Index",
	HandlerType: (*IndexServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Index",
			Handler:    _Index_Index_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "index/index.proto",
}
